"""TCP delivery of the task command generated by read_json."""
from __future__ import annotations

import socket


def send_task_command(host: str, port: int, command: str, timeout: float = 5.0) -> int:
    if not command or not command.strip():
        raise ValueError("任务指令为空，未发送")
    payload = command.encode("utf-8")
    with socket.create_connection((host, port), timeout=timeout) as connection:
        connection.sendall(payload)
    return len(payload)
