--- Auto generated by 'aubo_scope' v0.31.0-rc.6 2026-08-14 14:44:01
--- DO NOT MODIFY IT!
local app = {}
local aubo = require('aubo')
local sched = sched or aubo.sched
local math = aubo.math or math
local realtime = aubo.realtime or realtime

local sleep = sched.sleep
local thread = sched.thread
local sync = sched.sync
local run = sched.run
local kill = sched.kill
local halt = sched.halt

app.PRIORITY = 1000 -- set the app priority, which determines app execution order
app.VERSION = "0.1"
app.VENDOR = "Aubo Robotics"

function p_Untitled_0()
    local _ENV = sched.select_robot(1)
    setCollisionStopType(1)
    setCollisionLevel(6)
    setHardwareCustomParameters("handle_enable=true")
    setFreedriveDamp({0.5,0.5,0.5,0.5,0.5,0.5})
    setHomePosition({0,-0.2617993877991494,1.74532925199433,0.4363323129985824,1.570796326794897,0}    )
    modbusDeleteAllSignals()
    setDigitalInputActionDefault()
    setDigitalOutputRunstateDefault()
    setPayload(0, {0,0,0}, {0,0,0}, {0,0,0,0,0,0,0,0,0})
    setTcpOffset({0,0,0,0,0,0})
    setToolVoltageOutputDomain(24)
    setToolIoInput(0, false)
    setToolIoInput(1, false)
    setToolIoInput(2, false)
    setToolIoInput(3, false)
    flag = 2
    obj = 1
    obj1 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"4\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    obj2 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"2\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    obj3 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"1\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    obj4 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"5\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    obj5 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"3\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    obj6 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"6\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    action = 1
    tgt1 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"1\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    tgt2 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"5\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    tgt6 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"4\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    tgt3 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"3\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    tgt4 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"6\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    tgt5 = '"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"2\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\"\""'
    V_D_offs_x = '"1"'
    V_D_offs_y = '"-1"'
    V_D_offs_rz = '"10"'
    trans = 0
    rotation = 0
    Base= {0,0,0,0,0,0}
    Tool= {0,0,0,0,0,0}
    u70b9_0= {0.3655112870982485,-0.04022722239302076,1.026067750342817,1.565290344163739,0.3393465956517344,0.4999820158625549}
    setLabel(1, "初始变量")
    
    setLabel(2, "机器人编程")
    while true do
        setLabel(3, "action = 1")
        --subscript context start
        action = 1
        --subscript context end
        
        setLabel(4, "obj = 1")
        --subscript context start
        obj = 1
        --subscript context end
        
        setLabel(5, "photo_posB.lua")
        --subscript context start
        do
            function split(str, delimiter)  --声明字符分割函数
                if str==nil or str=='' or delimiter==nil then
                    return nil
                end
                local result = {}
                for match in (str..delimiter):gmatch("(.-)"..delimiter) do
                    table.insert(result, match)
                end
                return result
            end
            local socket = require("socket.core")
            local tcp = socket.tcp()
            local host = '192.168.1.10' --服务端IP地址
            local port = '6000' --串口号
            tcp:connect(host,port)
            tcp:settimeout(5)
            str1 = ""
            textmsg("ok1")
            --发送给服务端字符串
            tcp:send(action .. obj)
            textmsg("send: " .. action .. obj)
            textmsg("ok2")
            sleep(2)
                
            --接收服务端发送的字符串，只有接收到good，停止循环
            s, status, str1 = tcp:receive()
            if status == "timeout" then
                textmsg("接收超时")
                -- 可以继续其他操作或重试
            elseif s == nil then
                textmsg("接收错误: " .. tostring(status))
            end
            textmsg("receive: "..s)--打印recv
            textmsg("ok3")
            if (str1 ~= "") then
                textmsg("ok4")
                textmsg("receive: "..s)--打印recv
                table1 = split(s, ";")
                textmsg("ok5")
                V_D_offs_x = table1[2]
                V_D_offs_y = table1[3]
                V_D_offs_rz = table1[4]
                textmsg("ok6")
            end
            textmsg("receive: #0;" .. table1[2] .. ";" .. table1[3] .. ";" .. table1[4])
            tcp:close()
        end
        --subscript context end
        sched.cancel_point()
    end
end

function app:start(api)
  --
  self.api = api
  print("start---")
  p_Untitled_0()
end

function app:robot_error_handler(name, err)
  --
  print("An error hanppen to robot "..name)
end

-- return our app object
return app

